#!/bin/bash

set -e
set -x

env

. /usr/share/mkapp/functions

if [ "$PACKAGING" ]; then  
  rewrite
  build -F

  if [ "$PUBLISH" ]; then
    publish_debs
  fi
fi

if [ "$IMAGING" ]; then
  init
  update
  setup gpio
  finish '/opt/menucha-de' '["/opt/menucha-de/gpio", "-p", "80"]'
  cat Dockerfile
fi
